apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-hd-sm
  labels:
    k8s-app: label-hd-sm
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: label-hd-sm
  template:
    metadata: 
      labels:
        k8s-app: label-hd-sm
    spec:
      containers:
      - name: label-hd-sm
        image: nvidia/cuda:11.1.1-cudnn8-devel-ubuntu18.04
        command: ["sleep", "infinity"]
        volumeMounts:
          - mountPath: /mnt/data
            name: data
          - mountPath: /root/main
            name: nuscenes-ivannia-volume
          - mountPath: /dev/shm
            name: cache-volume
        resources:
          limits:
            memory: "32G"
            cpu: "3"
            ephemeral-storage: "2Ti"
            nvidia.com/gpu: 1
          requests:
             memory: "12G"
             cpu: "1"
             ephemeral-storage: "1Ti"
             nvidia.com/gpu: 1
      volumes:
        - name: nuscenes-ivannia-volume
          persistentVolumeClaim:
            claimName: nuscenes-ivannia-volume
        - name: data
          emptyDir: {}
        - emptyDir:
            medium: Memory
          name: cache-volume
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A10
                #- NVIDIA-GeForce-RTX-3090
                #- Tesla-V100-SXM2-32GB